name: Preview (clean)

on:
  pull_request:
    types: [closed]

jobs:
  teardown:
    # Run only from the original repository
    # Because this job requires secrets, which cannot be shared with forks
    if: github.event.pull_request.head.repo.full_name == github.repository
    uses: Qiskit/gh-actions/.github/workflows/code-engine-cleanup.yml@main
    with:
      code_engine_project: platypus-preview
      docker_image_name: platypus
    secrets:
      ibmcloud_account: ${{ secrets.IBMCLOUD_ACCOUNT }}
      ibmcloud_api_key: ${{ secrets.IBMCLOUD_API_KEY }}
